# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/JumpEvent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/JumpEvent.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18protobuf/JumpEvent.proto\"<\n\tJumpEvent\x12\x0f\n\x07\x61gentId\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x01\x12\x10\n\x08height_m\x18\x03 \x01(\x01\x62\x06proto3')
)




_JUMPEVENT = _descriptor.Descriptor(
  name='JumpEvent',
  full_name='JumpEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agentId', full_name='JumpEvent.agentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='JumpEvent.time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height_m', full_name='JumpEvent.height_m', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['JumpEvent'] = _JUMPEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JumpEvent = _reflection.GeneratedProtocolMessageType('JumpEvent', (_message.Message,), dict(
  DESCRIPTOR = _JUMPEVENT,
  __module__ = 'protobuf.JumpEvent_pb2'
  # @@protoc_insertion_point(class_scope:JumpEvent)
  ))
_sym_db.RegisterMessage(JumpEvent)


# @@protoc_insertion_point(module_scope)
