// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/EventBuffer.proto

package ch.dubernet.demopythonapi.simulation.protobuf;

public final class EventBufferOuterClass {
  private EventBufferOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventBufferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EventBuffer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    java.util.List<ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer> 
        getEventsList();
    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer getEvents(int index);
    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    java.util.List<? extends ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder> 
        getEventsOrBuilderList();
    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder getEventsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code EventBuffer}
   */
  public  static final class EventBuffer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EventBuffer)
      EventBufferOrBuilder {
    // Use EventBuffer.newBuilder() to construct.
    private EventBuffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventBuffer() {
      events_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EventBuffer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                events_ = new java.util.ArrayList<ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer>();
                mutable_bitField0_ |= 0x00000001;
              }
              events_.add(
                  input.readMessage(ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventBuffer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventBuffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer.class, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer.Builder.class);
    }

    public static final int EVENTS_FIELD_NUMBER = 1;
    private java.util.List<ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer> events_;
    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    public java.util.List<ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    public java.util.List<? extends ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .EventContainer events = 1;</code>
     */
    public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < events_.size(); i++) {
        output.writeMessage(1, events_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < events_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, events_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer)) {
        return super.equals(obj);
      }
      ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer other = (ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer) obj;

      boolean result = true;
      result = result && getEventsList()
          .equals(other.getEventsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getEventsCount() > 0) {
        hash = (37 * hash) + EVENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEventsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EventBuffer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EventBuffer)
        ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBufferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventBuffer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventBuffer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer.class, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer.Builder.class);
      }

      // Construct using ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEventsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventBuffer_descriptor;
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer getDefaultInstanceForType() {
        return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer.getDefaultInstance();
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer build() {
        ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer buildPartial() {
        ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer result = new ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer(this);
        int from_bitField0_ = bitField0_;
        if (eventsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            events_ = java.util.Collections.unmodifiableList(events_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.events_ = events_;
        } else {
          result.events_ = eventsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer) {
          return mergeFrom((ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer other) {
        if (other == ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer.getDefaultInstance()) return this;
        if (eventsBuilder_ == null) {
          if (!other.events_.isEmpty()) {
            if (events_.isEmpty()) {
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEventsIsMutable();
              events_.addAll(other.events_);
            }
            onChanged();
          }
        } else {
          if (!other.events_.isEmpty()) {
            if (eventsBuilder_.isEmpty()) {
              eventsBuilder_.dispose();
              eventsBuilder_ = null;
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000001);
              eventsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEventsFieldBuilder() : null;
            } else {
              eventsBuilder_.addAllMessages(other.events_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer> events_ =
        java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          events_ = new java.util.ArrayList<ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer>(events_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder> eventsBuilder_;

      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public java.util.List<ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer> getEventsList() {
        if (eventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(events_);
        } else {
          return eventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public int getEventsCount() {
        if (eventsBuilder_ == null) {
          return events_.size();
        } else {
          return eventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer getEvents(int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);
        } else {
          return eventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public Builder setEvents(
          int index, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.set(index, value);
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public Builder setEvents(
          int index, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public Builder addEvents(ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public Builder addEvents(
          int index, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(index, value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public Builder addEvents(
          ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public Builder addEvents(
          int index, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer> values) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, events_);
          onChanged();
        } else {
          eventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public Builder clearEvents() {
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public Builder removeEvents(int index) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.remove(index);
          onChanged();
        } else {
          eventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder getEventsBuilder(
          int index) {
        return getEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder getEventsOrBuilder(
          int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);  } else {
          return eventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public java.util.List<? extends ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder> 
           getEventsOrBuilderList() {
        if (eventsBuilder_ != null) {
          return eventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(events_);
        }
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder addEventsBuilder() {
        return getEventsFieldBuilder().addBuilder(
            ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.getDefaultInstance());
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder addEventsBuilder(
          int index) {
        return getEventsFieldBuilder().addBuilder(
            index, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.getDefaultInstance());
      }
      /**
       * <code>repeated .EventContainer events = 1;</code>
       */
      public java.util.List<ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder> 
           getEventsBuilderList() {
        return getEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder> 
          getEventsFieldBuilder() {
        if (eventsBuilder_ == null) {
          eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder>(
                  events_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        return eventsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:EventBuffer)
    }

    // @@protoc_insertion_point(class_scope:EventBuffer)
    private static final ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer();
    }

    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventBuffer>
        PARSER = new com.google.protobuf.AbstractParser<EventBuffer>() {
      public EventBuffer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EventBuffer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventBuffer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventBuffer> getParserForType() {
      return PARSER;
    }

    public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventBuffer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventContainerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EventContainer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .JumpEvent jumpEvent = 1;</code>
     */
    ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent getJumpEvent();
    /**
     * <code>optional .JumpEvent jumpEvent = 1;</code>
     */
    ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEventOrBuilder getJumpEventOrBuilder();

    /**
     * <code>optional .SingEvent singEvent = 2;</code>
     */
    ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent getSingEvent();
    /**
     * <code>optional .SingEvent singEvent = 2;</code>
     */
    ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEventOrBuilder getSingEventOrBuilder();

    /**
     * <code>optional .SpeakEvent speakEvent = 3;</code>
     */
    ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent getSpeakEvent();
    /**
     * <code>optional .SpeakEvent speakEvent = 3;</code>
     */
    ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEventOrBuilder getSpeakEventOrBuilder();

    public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.EventCase getEventCase();
  }
  /**
   * <pre>
   **
   * Acts as a kind of case class to be able to build the buffer
   * </pre>
   *
   * Protobuf type {@code EventContainer}
   */
  public  static final class EventContainer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EventContainer)
      EventContainerOrBuilder {
    // Use EventContainer.newBuilder() to construct.
    private EventContainer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventContainer() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EventContainer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.Builder subBuilder = null;
              if (eventCase_ == 1) {
                subBuilder = ((ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_).toBuilder();
              }
              event_ =
                  input.readMessage(ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 1;
              break;
            }
            case 18: {
              ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Builder subBuilder = null;
              if (eventCase_ == 2) {
                subBuilder = ((ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_).toBuilder();
              }
              event_ =
                  input.readMessage(ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 2;
              break;
            }
            case 26: {
              ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.Builder subBuilder = null;
              if (eventCase_ == 3) {
                subBuilder = ((ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_).toBuilder();
              }
              event_ =
                  input.readMessage(ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventContainer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.class, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder.class);
    }

    private int eventCase_ = 0;
    private java.lang.Object event_;
    public enum EventCase
        implements com.google.protobuf.Internal.EnumLite {
      JUMPEVENT(1),
      SINGEVENT(2),
      SPEAKEVENT(3),
      EVENT_NOT_SET(0);
      private final int value;
      private EventCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EventCase valueOf(int value) {
        return forNumber(value);
      }

      public static EventCase forNumber(int value) {
        switch (value) {
          case 1: return JUMPEVENT;
          case 2: return SINGEVENT;
          case 3: return SPEAKEVENT;
          case 0: return EVENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EventCase
    getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public static final int JUMPEVENT_FIELD_NUMBER = 1;
    /**
     * <code>optional .JumpEvent jumpEvent = 1;</code>
     */
    public ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent getJumpEvent() {
      if (eventCase_ == 1) {
         return (ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_;
      }
      return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.getDefaultInstance();
    }
    /**
     * <code>optional .JumpEvent jumpEvent = 1;</code>
     */
    public ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEventOrBuilder getJumpEventOrBuilder() {
      if (eventCase_ == 1) {
         return (ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_;
      }
      return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.getDefaultInstance();
    }

    public static final int SINGEVENT_FIELD_NUMBER = 2;
    /**
     * <code>optional .SingEvent singEvent = 2;</code>
     */
    public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent getSingEvent() {
      if (eventCase_ == 2) {
         return (ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_;
      }
      return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDefaultInstance();
    }
    /**
     * <code>optional .SingEvent singEvent = 2;</code>
     */
    public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEventOrBuilder getSingEventOrBuilder() {
      if (eventCase_ == 2) {
         return (ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_;
      }
      return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDefaultInstance();
    }

    public static final int SPEAKEVENT_FIELD_NUMBER = 3;
    /**
     * <code>optional .SpeakEvent speakEvent = 3;</code>
     */
    public ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent getSpeakEvent() {
      if (eventCase_ == 3) {
         return (ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_;
      }
      return ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.getDefaultInstance();
    }
    /**
     * <code>optional .SpeakEvent speakEvent = 3;</code>
     */
    public ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEventOrBuilder getSpeakEventOrBuilder() {
      if (eventCase_ == 3) {
         return (ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_;
      }
      return ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eventCase_ == 1) {
        output.writeMessage(1, (ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_);
      }
      if (eventCase_ == 2) {
        output.writeMessage(2, (ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_);
      }
      if (eventCase_ == 3) {
        output.writeMessage(3, (ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eventCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_);
      }
      if (eventCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_);
      }
      if (eventCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer)) {
        return super.equals(obj);
      }
      ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer other = (ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer) obj;

      boolean result = true;
      result = result && getEventCase().equals(
          other.getEventCase());
      if (!result) return false;
      switch (eventCase_) {
        case 1:
          result = result && getJumpEvent()
              .equals(other.getJumpEvent());
          break;
        case 2:
          result = result && getSingEvent()
              .equals(other.getSingEvent());
          break;
        case 3:
          result = result && getSpeakEvent()
              .equals(other.getSpeakEvent());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (eventCase_) {
        case 1:
          hash = (37 * hash) + JUMPEVENT_FIELD_NUMBER;
          hash = (53 * hash) + getJumpEvent().hashCode();
          break;
        case 2:
          hash = (37 * hash) + SINGEVENT_FIELD_NUMBER;
          hash = (53 * hash) + getSingEvent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + SPEAKEVENT_FIELD_NUMBER;
          hash = (53 * hash) + getSpeakEvent().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * Acts as a kind of case class to be able to build the buffer
     * </pre>
     *
     * Protobuf type {@code EventContainer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EventContainer)
        ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventContainer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventContainer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.class, ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.Builder.class);
      }

      // Construct using ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        eventCase_ = 0;
        event_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.internal_static_EventContainer_descriptor;
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer getDefaultInstanceForType() {
        return ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.getDefaultInstance();
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer build() {
        ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer buildPartial() {
        ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer result = new ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer(this);
        if (eventCase_ == 1) {
          if (jumpEventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = jumpEventBuilder_.build();
          }
        }
        if (eventCase_ == 2) {
          if (singEventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = singEventBuilder_.build();
          }
        }
        if (eventCase_ == 3) {
          if (speakEventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = speakEventBuilder_.build();
          }
        }
        result.eventCase_ = eventCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer) {
          return mergeFrom((ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer other) {
        if (other == ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer.getDefaultInstance()) return this;
        switch (other.getEventCase()) {
          case JUMPEVENT: {
            mergeJumpEvent(other.getJumpEvent());
            break;
          }
          case SINGEVENT: {
            mergeSingEvent(other.getSingEvent());
            break;
          }
          case SPEAKEVENT: {
            mergeSpeakEvent(other.getSpeakEvent());
            break;
          }
          case EVENT_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int eventCase_ = 0;
      private java.lang.Object event_;
      public EventCase
          getEventCase() {
        return EventCase.forNumber(
            eventCase_);
      }

      public Builder clearEvent() {
        eventCase_ = 0;
        event_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent, ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.Builder, ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEventOrBuilder> jumpEventBuilder_;
      /**
       * <code>optional .JumpEvent jumpEvent = 1;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent getJumpEvent() {
        if (jumpEventBuilder_ == null) {
          if (eventCase_ == 1) {
            return (ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_;
          }
          return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.getDefaultInstance();
        } else {
          if (eventCase_ == 1) {
            return jumpEventBuilder_.getMessage();
          }
          return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.getDefaultInstance();
        }
      }
      /**
       * <code>optional .JumpEvent jumpEvent = 1;</code>
       */
      public Builder setJumpEvent(ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent value) {
        if (jumpEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          jumpEventBuilder_.setMessage(value);
        }
        eventCase_ = 1;
        return this;
      }
      /**
       * <code>optional .JumpEvent jumpEvent = 1;</code>
       */
      public Builder setJumpEvent(
          ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.Builder builderForValue) {
        if (jumpEventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          jumpEventBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 1;
        return this;
      }
      /**
       * <code>optional .JumpEvent jumpEvent = 1;</code>
       */
      public Builder mergeJumpEvent(ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent value) {
        if (jumpEventBuilder_ == null) {
          if (eventCase_ == 1 &&
              event_ != ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.getDefaultInstance()) {
            event_ = ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.newBuilder((ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 1) {
            jumpEventBuilder_.mergeFrom(value);
          }
          jumpEventBuilder_.setMessage(value);
        }
        eventCase_ = 1;
        return this;
      }
      /**
       * <code>optional .JumpEvent jumpEvent = 1;</code>
       */
      public Builder clearJumpEvent() {
        if (jumpEventBuilder_ == null) {
          if (eventCase_ == 1) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 1) {
            eventCase_ = 0;
            event_ = null;
          }
          jumpEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .JumpEvent jumpEvent = 1;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.Builder getJumpEventBuilder() {
        return getJumpEventFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .JumpEvent jumpEvent = 1;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEventOrBuilder getJumpEventOrBuilder() {
        if ((eventCase_ == 1) && (jumpEventBuilder_ != null)) {
          return jumpEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 1) {
            return (ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_;
          }
          return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.getDefaultInstance();
        }
      }
      /**
       * <code>optional .JumpEvent jumpEvent = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent, ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.Builder, ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEventOrBuilder> 
          getJumpEventFieldBuilder() {
        if (jumpEventBuilder_ == null) {
          if (!(eventCase_ == 1)) {
            event_ = ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.getDefaultInstance();
          }
          jumpEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent, ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.Builder, ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEventOrBuilder>(
                  (ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 1;
        onChanged();;
        return jumpEventBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent, ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Builder, ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEventOrBuilder> singEventBuilder_;
      /**
       * <code>optional .SingEvent singEvent = 2;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent getSingEvent() {
        if (singEventBuilder_ == null) {
          if (eventCase_ == 2) {
            return (ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_;
          }
          return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDefaultInstance();
        } else {
          if (eventCase_ == 2) {
            return singEventBuilder_.getMessage();
          }
          return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SingEvent singEvent = 2;</code>
       */
      public Builder setSingEvent(ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent value) {
        if (singEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          singEventBuilder_.setMessage(value);
        }
        eventCase_ = 2;
        return this;
      }
      /**
       * <code>optional .SingEvent singEvent = 2;</code>
       */
      public Builder setSingEvent(
          ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Builder builderForValue) {
        if (singEventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          singEventBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 2;
        return this;
      }
      /**
       * <code>optional .SingEvent singEvent = 2;</code>
       */
      public Builder mergeSingEvent(ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent value) {
        if (singEventBuilder_ == null) {
          if (eventCase_ == 2 &&
              event_ != ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDefaultInstance()) {
            event_ = ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.newBuilder((ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 2) {
            singEventBuilder_.mergeFrom(value);
          }
          singEventBuilder_.setMessage(value);
        }
        eventCase_ = 2;
        return this;
      }
      /**
       * <code>optional .SingEvent singEvent = 2;</code>
       */
      public Builder clearSingEvent() {
        if (singEventBuilder_ == null) {
          if (eventCase_ == 2) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 2) {
            eventCase_ = 0;
            event_ = null;
          }
          singEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .SingEvent singEvent = 2;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Builder getSingEventBuilder() {
        return getSingEventFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SingEvent singEvent = 2;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEventOrBuilder getSingEventOrBuilder() {
        if ((eventCase_ == 2) && (singEventBuilder_ != null)) {
          return singEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 2) {
            return (ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_;
          }
          return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SingEvent singEvent = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent, ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Builder, ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEventOrBuilder> 
          getSingEventFieldBuilder() {
        if (singEventBuilder_ == null) {
          if (!(eventCase_ == 2)) {
            event_ = ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDefaultInstance();
          }
          singEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent, ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Builder, ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEventOrBuilder>(
                  (ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 2;
        onChanged();;
        return singEventBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent, ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.Builder, ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEventOrBuilder> speakEventBuilder_;
      /**
       * <code>optional .SpeakEvent speakEvent = 3;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent getSpeakEvent() {
        if (speakEventBuilder_ == null) {
          if (eventCase_ == 3) {
            return (ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_;
          }
          return ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.getDefaultInstance();
        } else {
          if (eventCase_ == 3) {
            return speakEventBuilder_.getMessage();
          }
          return ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SpeakEvent speakEvent = 3;</code>
       */
      public Builder setSpeakEvent(ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent value) {
        if (speakEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          speakEventBuilder_.setMessage(value);
        }
        eventCase_ = 3;
        return this;
      }
      /**
       * <code>optional .SpeakEvent speakEvent = 3;</code>
       */
      public Builder setSpeakEvent(
          ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.Builder builderForValue) {
        if (speakEventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          speakEventBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 3;
        return this;
      }
      /**
       * <code>optional .SpeakEvent speakEvent = 3;</code>
       */
      public Builder mergeSpeakEvent(ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent value) {
        if (speakEventBuilder_ == null) {
          if (eventCase_ == 3 &&
              event_ != ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.getDefaultInstance()) {
            event_ = ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.newBuilder((ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 3) {
            speakEventBuilder_.mergeFrom(value);
          }
          speakEventBuilder_.setMessage(value);
        }
        eventCase_ = 3;
        return this;
      }
      /**
       * <code>optional .SpeakEvent speakEvent = 3;</code>
       */
      public Builder clearSpeakEvent() {
        if (speakEventBuilder_ == null) {
          if (eventCase_ == 3) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 3) {
            eventCase_ = 0;
            event_ = null;
          }
          speakEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .SpeakEvent speakEvent = 3;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.Builder getSpeakEventBuilder() {
        return getSpeakEventFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SpeakEvent speakEvent = 3;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEventOrBuilder getSpeakEventOrBuilder() {
        if ((eventCase_ == 3) && (speakEventBuilder_ != null)) {
          return speakEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 3) {
            return (ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_;
          }
          return ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SpeakEvent speakEvent = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent, ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.Builder, ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEventOrBuilder> 
          getSpeakEventFieldBuilder() {
        if (speakEventBuilder_ == null) {
          if (!(eventCase_ == 3)) {
            event_ = ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.getDefaultInstance();
          }
          speakEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent, ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent.Builder, ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEventOrBuilder>(
                  (ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.SpeakEvent) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 3;
        onChanged();;
        return speakEventBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:EventContainer)
    }

    // @@protoc_insertion_point(class_scope:EventContainer)
    private static final ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer();
    }

    public static ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventContainer>
        PARSER = new com.google.protobuf.AbstractParser<EventContainer>() {
      public EventContainer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EventContainer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventContainer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventContainer> getParserForType() {
      return PARSER;
    }

    public ch.dubernet.demopythonapi.simulation.protobuf.EventBufferOuterClass.EventContainer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EventBuffer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EventBuffer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EventContainer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EventContainer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032protobuf/EventBuffer.proto\032\030protobuf/J" +
      "umpEvent.proto\032\030protobuf/SingEvent.proto" +
      "\032\031protobuf/SpeakEvent.proto\".\n\013EventBuff" +
      "er\022\037\n\006events\030\001 \003(\0132\017.EventContainer\"~\n\016E" +
      "ventContainer\022\037\n\tjumpEvent\030\001 \001(\0132\n.JumpE" +
      "ventH\000\022\037\n\tsingEvent\030\002 \001(\0132\n.SingEventH\000\022" +
      "!\n\nspeakEvent\030\003 \001(\0132\013.SpeakEventH\000B\007\n\005ev" +
      "entB/\n-ch.dubernet.demopythonapi.simulat" +
      "ion.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.getDescriptor(),
          ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.getDescriptor(),
          ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.getDescriptor(),
        }, assigner);
    internal_static_EventBuffer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EventBuffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EventBuffer_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_EventContainer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EventContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EventContainer_descriptor,
        new java.lang.String[] { "JumpEvent", "SingEvent", "SpeakEvent", "Event", });
    ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.getDescriptor();
    ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.getDescriptor();
    ch.dubernet.demopythonapi.simulation.protobuf.SpeakEventOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
