// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JumpEvent.proto

package ch.dubernet.demopythonapi.simulation.protobuf;

public final class JumpEventOuterClass {
  private JumpEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JumpEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JumpEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string agentId = 1;</code>
     */
    java.lang.String getAgentId();
    /**
     * <code>optional string agentId = 1;</code>
     */
    com.google.protobuf.ByteString
        getAgentIdBytes();

    /**
     * <code>optional double time = 2;</code>
     */
    double getTime();

    /**
     * <code>optional double height_m = 3;</code>
     */
    double getHeightM();
  }
  /**
   * Protobuf type {@code JumpEvent}
   */
  public  static final class JumpEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JumpEvent)
      JumpEventOrBuilder {
    // Use JumpEvent.newBuilder() to construct.
    private JumpEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JumpEvent() {
      agentId_ = "";
      time_ = 0D;
      heightM_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private JumpEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              agentId_ = s;
              break;
            }
            case 17: {

              time_ = input.readDouble();
              break;
            }
            case 25: {

              heightM_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.internal_static_JumpEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.internal_static_JumpEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.class, ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.Builder.class);
    }

    public static final int AGENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object agentId_;
    /**
     * <code>optional string agentId = 1;</code>
     */
    public java.lang.String getAgentId() {
      java.lang.Object ref = agentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agentId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string agentId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAgentIdBytes() {
      java.lang.Object ref = agentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private double time_;
    /**
     * <code>optional double time = 2;</code>
     */
    public double getTime() {
      return time_;
    }

    public static final int HEIGHT_M_FIELD_NUMBER = 3;
    private double heightM_;
    /**
     * <code>optional double height_m = 3;</code>
     */
    public double getHeightM() {
      return heightM_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAgentIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, agentId_);
      }
      if (time_ != 0D) {
        output.writeDouble(2, time_);
      }
      if (heightM_ != 0D) {
        output.writeDouble(3, heightM_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAgentIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, agentId_);
      }
      if (time_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, time_);
      }
      if (heightM_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, heightM_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent)) {
        return super.equals(obj);
      }
      ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent other = (ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) obj;

      boolean result = true;
      result = result && getAgentId()
          .equals(other.getAgentId());
      result = result && (
          java.lang.Double.doubleToLongBits(getTime())
          == java.lang.Double.doubleToLongBits(
              other.getTime()));
      result = result && (
          java.lang.Double.doubleToLongBits(getHeightM())
          == java.lang.Double.doubleToLongBits(
              other.getHeightM()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AGENTID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentId().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTime()));
      hash = (37 * hash) + HEIGHT_M_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHeightM()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JumpEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JumpEvent)
        ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.internal_static_JumpEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.internal_static_JumpEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.class, ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.Builder.class);
      }

      // Construct using ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        agentId_ = "";

        time_ = 0D;

        heightM_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.internal_static_JumpEvent_descriptor;
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent getDefaultInstanceForType() {
        return ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.getDefaultInstance();
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent build() {
        ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent buildPartial() {
        ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent result = new ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent(this);
        result.agentId_ = agentId_;
        result.time_ = time_;
        result.heightM_ = heightM_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) {
          return mergeFrom((ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent other) {
        if (other == ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent.getDefaultInstance()) return this;
        if (!other.getAgentId().isEmpty()) {
          agentId_ = other.agentId_;
          onChanged();
        }
        if (other.getTime() != 0D) {
          setTime(other.getTime());
        }
        if (other.getHeightM() != 0D) {
          setHeightM(other.getHeightM());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object agentId_ = "";
      /**
       * <code>optional string agentId = 1;</code>
       */
      public java.lang.String getAgentId() {
        java.lang.Object ref = agentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          agentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string agentId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAgentIdBytes() {
        java.lang.Object ref = agentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          agentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string agentId = 1;</code>
       */
      public Builder setAgentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        agentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string agentId = 1;</code>
       */
      public Builder clearAgentId() {
        
        agentId_ = getDefaultInstance().getAgentId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string agentId = 1;</code>
       */
      public Builder setAgentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        agentId_ = value;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <code>optional double time = 2;</code>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>optional double time = 2;</code>
       */
      public Builder setTime(double value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = 0D;
        onChanged();
        return this;
      }

      private double heightM_ ;
      /**
       * <code>optional double height_m = 3;</code>
       */
      public double getHeightM() {
        return heightM_;
      }
      /**
       * <code>optional double height_m = 3;</code>
       */
      public Builder setHeightM(double value) {
        
        heightM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double height_m = 3;</code>
       */
      public Builder clearHeightM() {
        
        heightM_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:JumpEvent)
    }

    // @@protoc_insertion_point(class_scope:JumpEvent)
    private static final ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent();
    }

    public static ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JumpEvent>
        PARSER = new com.google.protobuf.AbstractParser<JumpEvent>() {
      public JumpEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new JumpEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JumpEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JumpEvent> getParserForType() {
      return PARSER;
    }

    public ch.dubernet.demopythonapi.simulation.protobuf.JumpEventOuterClass.JumpEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JumpEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JumpEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017JumpEvent.proto\"<\n\tJumpEvent\022\017\n\007agentI" +
      "d\030\001 \001(\t\022\014\n\004time\030\002 \001(\001\022\020\n\010height_m\030\003 \001(\001B" +
      "/\n-ch.dubernet.demopythonapi.simulation." +
      "protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JumpEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JumpEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JumpEvent_descriptor,
        new java.lang.String[] { "AgentId", "Time", "HeightM", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
