// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/SingEvent.proto

package ch.dubernet.demopythonapi.simulation.protobuf;

public final class SingEventOuterClass {
  private SingEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SingEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SingEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string agentId = 1;</code>
     */
    java.lang.String getAgentId();
    /**
     * <code>optional string agentId = 1;</code>
     */
    com.google.protobuf.ByteString
        getAgentIdBytes();

    /**
     * <code>optional double time = 2;</code>
     */
    double getTime();

    /**
     * <code>optional .SingEvent.Song song = 3;</code>
     */
    int getSongValue();
    /**
     * <code>optional .SingEvent.Song song = 3;</code>
     */
    ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song getSong();
  }
  /**
   * Protobuf type {@code SingEvent}
   */
  public  static final class SingEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SingEvent)
      SingEventOrBuilder {
    // Use SingEvent.newBuilder() to construct.
    private SingEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SingEvent() {
      agentId_ = "";
      time_ = 0D;
      song_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SingEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              agentId_ = s;
              break;
            }
            case 17: {

              time_ = input.readDouble();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              song_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.internal_static_SingEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.internal_static_SingEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.class, ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Builder.class);
    }

    /**
     * Protobuf enum {@code SingEvent.Song}
     */
    public enum Song
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OLD_MC_DONALDS = 0;</code>
       */
      OLD_MC_DONALDS(0),
      /**
       * <code>IF_YOU_ARE_HAPPY = 1;</code>
       */
      IF_YOU_ARE_HAPPY(1),
      /**
       * <code>NINETY_NINE_BOTTLES = 2;</code>
       */
      NINETY_NINE_BOTTLES(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>OLD_MC_DONALDS = 0;</code>
       */
      public static final int OLD_MC_DONALDS_VALUE = 0;
      /**
       * <code>IF_YOU_ARE_HAPPY = 1;</code>
       */
      public static final int IF_YOU_ARE_HAPPY_VALUE = 1;
      /**
       * <code>NINETY_NINE_BOTTLES = 2;</code>
       */
      public static final int NINETY_NINE_BOTTLES_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Song valueOf(int value) {
        return forNumber(value);
      }

      public static Song forNumber(int value) {
        switch (value) {
          case 0: return OLD_MC_DONALDS;
          case 1: return IF_YOU_ARE_HAPPY;
          case 2: return NINETY_NINE_BOTTLES;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Song>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Song> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Song>() {
              public Song findValueByNumber(int number) {
                return Song.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDescriptor().getEnumTypes().get(0);
      }

      private static final Song[] VALUES = values();

      public static Song valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Song(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SingEvent.Song)
    }

    public static final int AGENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object agentId_;
    /**
     * <code>optional string agentId = 1;</code>
     */
    public java.lang.String getAgentId() {
      java.lang.Object ref = agentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agentId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string agentId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAgentIdBytes() {
      java.lang.Object ref = agentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private double time_;
    /**
     * <code>optional double time = 2;</code>
     */
    public double getTime() {
      return time_;
    }

    public static final int SONG_FIELD_NUMBER = 3;
    private int song_;
    /**
     * <code>optional .SingEvent.Song song = 3;</code>
     */
    public int getSongValue() {
      return song_;
    }
    /**
     * <code>optional .SingEvent.Song song = 3;</code>
     */
    public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song getSong() {
      ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song result = ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song.valueOf(song_);
      return result == null ? ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAgentIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, agentId_);
      }
      if (time_ != 0D) {
        output.writeDouble(2, time_);
      }
      if (song_ != ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song.OLD_MC_DONALDS.getNumber()) {
        output.writeEnum(3, song_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAgentIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, agentId_);
      }
      if (time_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, time_);
      }
      if (song_ != ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song.OLD_MC_DONALDS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, song_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent)) {
        return super.equals(obj);
      }
      ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent other = (ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) obj;

      boolean result = true;
      result = result && getAgentId()
          .equals(other.getAgentId());
      result = result && (
          java.lang.Double.doubleToLongBits(getTime())
          == java.lang.Double.doubleToLongBits(
              other.getTime()));
      result = result && song_ == other.song_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AGENTID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentId().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTime()));
      hash = (37 * hash) + SONG_FIELD_NUMBER;
      hash = (53 * hash) + song_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SingEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SingEvent)
        ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.internal_static_SingEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.internal_static_SingEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.class, ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Builder.class);
      }

      // Construct using ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        agentId_ = "";

        time_ = 0D;

        song_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.internal_static_SingEvent_descriptor;
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent getDefaultInstanceForType() {
        return ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDefaultInstance();
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent build() {
        ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent buildPartial() {
        ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent result = new ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent(this);
        result.agentId_ = agentId_;
        result.time_ = time_;
        result.song_ = song_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) {
          return mergeFrom((ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent other) {
        if (other == ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.getDefaultInstance()) return this;
        if (!other.getAgentId().isEmpty()) {
          agentId_ = other.agentId_;
          onChanged();
        }
        if (other.getTime() != 0D) {
          setTime(other.getTime());
        }
        if (other.song_ != 0) {
          setSongValue(other.getSongValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object agentId_ = "";
      /**
       * <code>optional string agentId = 1;</code>
       */
      public java.lang.String getAgentId() {
        java.lang.Object ref = agentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          agentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string agentId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAgentIdBytes() {
        java.lang.Object ref = agentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          agentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string agentId = 1;</code>
       */
      public Builder setAgentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        agentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string agentId = 1;</code>
       */
      public Builder clearAgentId() {
        
        agentId_ = getDefaultInstance().getAgentId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string agentId = 1;</code>
       */
      public Builder setAgentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        agentId_ = value;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <code>optional double time = 2;</code>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>optional double time = 2;</code>
       */
      public Builder setTime(double value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = 0D;
        onChanged();
        return this;
      }

      private int song_ = 0;
      /**
       * <code>optional .SingEvent.Song song = 3;</code>
       */
      public int getSongValue() {
        return song_;
      }
      /**
       * <code>optional .SingEvent.Song song = 3;</code>
       */
      public Builder setSongValue(int value) {
        song_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SingEvent.Song song = 3;</code>
       */
      public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song getSong() {
        ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song result = ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song.valueOf(song_);
        return result == null ? ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .SingEvent.Song song = 3;</code>
       */
      public Builder setSong(ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent.Song value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        song_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .SingEvent.Song song = 3;</code>
       */
      public Builder clearSong() {
        
        song_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SingEvent)
    }

    // @@protoc_insertion_point(class_scope:SingEvent)
    private static final ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent();
    }

    public static ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SingEvent>
        PARSER = new com.google.protobuf.AbstractParser<SingEvent>() {
      public SingEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SingEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SingEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SingEvent> getParserForType() {
      return PARSER;
    }

    public ch.dubernet.demopythonapi.simulation.protobuf.SingEventOuterClass.SingEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SingEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SingEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030protobuf/SingEvent.proto\"\224\001\n\tSingEvent" +
      "\022\017\n\007agentId\030\001 \001(\t\022\014\n\004time\030\002 \001(\001\022\035\n\004song\030" +
      "\003 \001(\0162\017.SingEvent.Song\"I\n\004Song\022\022\n\016OLD_MC" +
      "_DONALDS\020\000\022\024\n\020IF_YOU_ARE_HAPPY\020\001\022\027\n\023NINE" +
      "TY_NINE_BOTTLES\020\002B/\n-ch.dubernet.demopyt" +
      "honapi.simulation.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SingEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SingEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SingEvent_descriptor,
        new java.lang.String[] { "AgentId", "Time", "Song", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
