# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/EventBuffer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import JumpEvent_pb2 as protobuf_dot_JumpEvent__pb2
from protobuf import SingEvent_pb2 as protobuf_dot_SingEvent__pb2
from protobuf import SpeakEvent_pb2 as protobuf_dot_SpeakEvent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/EventBuffer.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1aprotobuf/EventBuffer.proto\x1a\x18protobuf/JumpEvent.proto\x1a\x18protobuf/SingEvent.proto\x1a\x19protobuf/SpeakEvent.proto\".\n\x0b\x45ventBuffer\x12\x1f\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x0f.EventContainer\"~\n\x0e\x45ventContainer\x12\x1f\n\tjumpEvent\x18\x01 \x01(\x0b\x32\n.JumpEventH\x00\x12\x1f\n\tsingEvent\x18\x02 \x01(\x0b\x32\n.SingEventH\x00\x12!\n\nspeakEvent\x18\x03 \x01(\x0b\x32\x0b.SpeakEventH\x00\x42\x07\n\x05\x65ventB/\n-ch.dubernet.demopythonapi.simulation.protobufb\x06proto3')
  ,
  dependencies=[protobuf_dot_JumpEvent__pb2.DESCRIPTOR,protobuf_dot_SingEvent__pb2.DESCRIPTOR,protobuf_dot_SpeakEvent__pb2.DESCRIPTOR,])




_EVENTBUFFER = _descriptor.Descriptor(
  name='EventBuffer',
  full_name='EventBuffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='EventBuffer.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=155,
)


_EVENTCONTAINER = _descriptor.Descriptor(
  name='EventContainer',
  full_name='EventContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jumpEvent', full_name='EventContainer.jumpEvent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='singEvent', full_name='EventContainer.singEvent', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speakEvent', full_name='EventContainer.speakEvent', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='EventContainer.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=157,
  serialized_end=283,
)

_EVENTBUFFER.fields_by_name['events'].message_type = _EVENTCONTAINER
_EVENTCONTAINER.fields_by_name['jumpEvent'].message_type = protobuf_dot_JumpEvent__pb2._JUMPEVENT
_EVENTCONTAINER.fields_by_name['singEvent'].message_type = protobuf_dot_SingEvent__pb2._SINGEVENT
_EVENTCONTAINER.fields_by_name['speakEvent'].message_type = protobuf_dot_SpeakEvent__pb2._SPEAKEVENT
_EVENTCONTAINER.oneofs_by_name['event'].fields.append(
  _EVENTCONTAINER.fields_by_name['jumpEvent'])
_EVENTCONTAINER.fields_by_name['jumpEvent'].containing_oneof = _EVENTCONTAINER.oneofs_by_name['event']
_EVENTCONTAINER.oneofs_by_name['event'].fields.append(
  _EVENTCONTAINER.fields_by_name['singEvent'])
_EVENTCONTAINER.fields_by_name['singEvent'].containing_oneof = _EVENTCONTAINER.oneofs_by_name['event']
_EVENTCONTAINER.oneofs_by_name['event'].fields.append(
  _EVENTCONTAINER.fields_by_name['speakEvent'])
_EVENTCONTAINER.fields_by_name['speakEvent'].containing_oneof = _EVENTCONTAINER.oneofs_by_name['event']
DESCRIPTOR.message_types_by_name['EventBuffer'] = _EVENTBUFFER
DESCRIPTOR.message_types_by_name['EventContainer'] = _EVENTCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventBuffer = _reflection.GeneratedProtocolMessageType('EventBuffer', (_message.Message,), dict(
  DESCRIPTOR = _EVENTBUFFER,
  __module__ = 'protobuf.EventBuffer_pb2'
  # @@protoc_insertion_point(class_scope:EventBuffer)
  ))
_sym_db.RegisterMessage(EventBuffer)

EventContainer = _reflection.GeneratedProtocolMessageType('EventContainer', (_message.Message,), dict(
  DESCRIPTOR = _EVENTCONTAINER,
  __module__ = 'protobuf.EventBuffer_pb2'
  # @@protoc_insertion_point(class_scope:EventContainer)
  ))
_sym_db.RegisterMessage(EventContainer)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n-ch.dubernet.demopythonapi.simulation.protobuf'))
# @@protoc_insertion_point(module_scope)
